name: Cypress Tests

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master  

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      # Checa o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Configura o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Define a versão do Node.js, pode ser alterado conforme necessário.

      # Instala as dependências do projeto
      - name: Install dependencies
        run: |
          npm install

      # Instala o Cypress
      - name: Install Cypress
        run: |
          npm install cypress

      # Executa os testes do Cypress
      - name: Run Cypress tests
        run: |
          npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/reports

      # Faz o upload do relatório como artefato da pipeline
      - name: Upload Cypress Test Results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-report
          path: cypress/reports
